package jwt

import (
	"context"
	"fmt"

	"github.com/K-H-Tech/apm/internal/models"
	"github.com/golang-jwt/jwt/v5"
)

// JWT will implement JWT contract
type JWT struct {
	secretKey []byte
}

// NewJWT is the JWT factory method
func NewJWT(secretKey string) *JWT {
	if len(secretKey) < 64 {
		panic("JWT secret key must be at least 64 bytes for HS512")
	}
	return &JWT{
		secretKey: []byte(secretKey),
	}
}

// Generate will issue a token based the given models.JWT input model
//
// this function does not apply any validation.
//
// all the validation must be applied in handlers, middlewares and services
func (j *JWT) Generate(ctx context.Context, claims *models.JWT) (string, error) {
	token := jwt.NewWithClaims(jwt.SigningMethodHS512, claims)
	return token.SignedString(j.secretKey)
}

// Verify will verify a token string. it will decode the token and return the claims if it was generated by us before.
//
// this method does not apply any validation. it will decode all tokens that been generated by us.
//
// all validation must be applied in handlers, middlewares and services.
func (j *JWT) Verify(ctx context.Context, token string) (*models.JWT, error) {
	jwtToken, err := jwt.ParseWithClaims(token, &models.JWT{}, func(t *jwt.Token) (interface{}, error) {
		if _, ok := t.Method.(*jwt.SigningMethodHMAC); !ok {
			return nil, fmt.Errorf("Unexpected signing method: %v", t.Header["alg"])
		}
		return j.secretKey, nil
	})
	if err != nil {
		return nil, fmt.Errorf("JWT. error at parsing the token: %w", err)
	}

	if jwtToken == nil || !jwtToken.Valid {
		return nil, fmt.Errorf("JWT. token is invalid")
	}

	claims, ok := jwtToken.Claims.(*models.JWT)
	if !ok {
		return nil, fmt.Errorf("JWT. error at asserting the claims to models.JWT")
	}

	return claims, nil
}
