services:
  mariadb:
    # connect to container terminal: docker-compose -f docker/docker-compose.yaml exec mariadb mysql -u admin -p -D tax_manager
    image: mariadb:lts
    command: "--default-authentication-plugin=mysql_native_password"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=tax_manager
      - MARIADB_DATABASE=tax_manager
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin_password
    ports:
      - 3306:3306
    volumes:
      - ./db_data/mariadb:/var/lib/mysql
      - ../docs/sql_ddls:/docker-entrypoint-initdb.d

  mongodb:
    # connect to container terminal: docker-compose -f docker/docker-compose.yaml exec mongodb mongo -u admin -p admin_password --authenticationDatabase admin
    image: mongodb/mongodb-community-server:4.4.15-ubuntu2004
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin_password
      MONGO_INITDB_DATABASE: tax_manager
    volumes:
      - ./db_data/mongodb:/data/db

  cache:
    # connect to container terminal: docker-compose -f docker/docker-compose.yaml exec cache redis-cli
    image: redis:7.2.4-alpine3.19
    command: redis-server --save 20 1 --loglevel warning
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./db_data/redis:/data
