package contract

import (
	"context"

	"github.com/K-H-Tech/apm/internal/models"
)

// JWT will wrap the json web token methods and behavior
type JWT interface {
	// Generate will issue a token based the given models.JWT input model
	//
	// this function does not apply any validation.
	//
	// all the validation must be applied in handlers, middlewares and services
	Generate(ctx context.Context, claims *models.JWT) (string, error)

	// Verify will verify a token string. it will decode the token and return the claims if it was generated by us before.
	//
	// this method does not apply any validation. it will decode all tokens that been generated by us.
	//
	// all validation must be applied in handlers, middlewares and services.
	Verify(ctx context.Context, token string) (*models.JWT, error)
}
